---

- name: copy defaults
  ansible.builtin.copy:
    src: defaults
    dest: /etc/default/bind9
    owner: root
    group: root
    mode: 0644
  notify: "restart bind9"

- name: copy named.conf
  ansible.builtin.copy:
    src: named.conf
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: 0644
  notify: "restart bind9"

- name: generate named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  notify: "restart bind9"

- name: generate named.conf.local (master)
  ansible.builtin.template:
    src: named.conf.local.master.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0644
  when: dns_server_type == "master"
  notify: "restart bind9"

- name: generate named.conf.local (slave)
  ansible.builtin.template:
    src: named.conf.local.slave.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0644
  when: dns_server_type == "slave"
  notify: "restart bind9"

- name: generate domain zone
  ansible.builtin.template:
    src: zone_db.j2
    dest: /etc/bind/db.{{ domain }}
    owner: root
    group: root
    mode: 0644
    validate: named-checkzone {{ domain }} %s
  vars:
    ptr_zone: False
  when: dns_server_type == "master"
  notify: "reload bind9"

- name: generate reverse lookup zones
  ansible.builtin.template:
    src: zone_db.j2
    dest: /etc/bind/db.{{ item }}
    owner: root
    group: root
    mode: 0644
    validate: named-checkzone {{ ".".join(item.split(".")[::-1]) }}.in-addr.arpa %s
  vars:
    ptr_zone: True
  loop: "{{ dns_ip_subnets }}"
  when: dns_server_type == "master"
  notify: "reload bind9"

- name: generate rpz
  ansible.builtin.template:
    src: zone_rpz.j2
    dest: /etc/bind/db.rpz
    owner: root
    group: root
    mode: 0644
    validate: named-checkzone rpz %s
  when: dns_server_type == "master"
  notify: "reload bind9"