---

- name: install bind9
  apt:
    name: ["bind9", "bind9utils", "dnsutils"]
    state: present
    
- name: delete default config files
  file:
    path: "/etc/bind/{{ item }}"
    state: absent
  with_items:
    - db.127
    - db.empty
    - db.0
    - db.255
    - db.local
    - named.conf.default-zones
    - zones.rfc1918